import Projects from '../Projects/Proyects'

export const projects = [
  {
    id: '1',
    name: 'the mistery fox',
    thumbnail: '/images/the-mistery-fox.png',
    screenshots: [
      '/images/screenshots/the-mistery-fox/the-mistery-fox-1.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-2.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-3.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-4.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-5.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-6.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-7.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-8.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-9.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-10.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-11.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-12.png',
      '/images/screenshots/the-mistery-fox/the-mistery-fox-13.png',
    ],
    description: {
      es: 'The mistery fox es una boutique de libros que ofrece una experiencia única. Inspirate y disfruta sus increíbles historias. E-commerce Full-Stack con autenticación.',
      en: 'The mistery fox is a book boutique which offers an unique experience. Get inspired and enjoy their incredible stories. Full-Stack e-commerce with user authentication',
    },
    features: {
      es: [
        'Proceso de compra completamente funcional conectado con pasarela de pago.',
        'Servicio de autenticación y autorización que incluye registro de usuarios, inicio y cierre de sesión, cambio de contraseña y cambio de rol entre usuario normal y premium.',
        'Rol de usuario premium con posibilidad de crear, modificar o eliminar sus propios productos.',
        'Rol de administrador con permisos elevados.',
        'Acceso a los productos a través de base de datos de MongoDB.',
        'Paginación de productos y filtrado por categorías.',
        'Almacenamiento en base de datos de usuarios, productos, carritos y tickets de compra.',
        'Servicio de mailing. Se recibe un email al registrar un usuario, al realizar una compra, al solicitar un cambio de contraseña y al eliminarse un producto de un usuario premium.',
        'Servicio de subida de archivos. Foto de perfil, imágenes de producto y documentos para actualizar el usuario a premium. ',
        'Buena experiencia de usuario, diseño cuidado y atención a los detalles.',
        'Completamente responsive. Se adapta a todas las pantallas.',
      ],
      en: [
        'Fully functional e-commerce connected to a payment processing platform.',
        'Authentication and authorization service that includes user registration, login and logout, password change and role change between normal and premium user.',
        'Premium role which can create, update or delete its own products.',
        'Administrator role with elevated permissions.',
        'Products are accesed through the MongoDB database.',
        'Products pagination and filter by category.',
        'Database persistance for users, products, carts and tickets.',
        "Mailing service for user registration, checkout, password change and when a premium user's product gets deleted.",
        'File upload service. Profile picture, product images and documents to upgrade to premium.',
        'Good user experience, polished design and attention to detail.',
        'Completely responsive.',
      ],
    },
    technologies: ['Node.js', 'Express', 'MongoDB', 'React', 'TailwindCSS'],
    github: 'https://github.com/Gonzalo-Coradello/the-mistery-fox_ecommerce',
    backend: 'https://github.com/Gonzalo-Coradello/backend-ecommerce',
    deploy: 'https://themisteryfox.vercel.app',
    credits: {
      es: 'Diseño, branding y logo: Talia Laborde',
      en: 'Branding, logo and design: Talia Laborde',
    },
  },
  {
    id: '2',
    name: 'Pokéteams',
    thumbnail: '/images/poketeams.png',
    screenshots: [
      '/images/screenshots/poketeams/poketeams1.png',
      '/images/screenshots/poketeams/poketeams2.png',
      '/images/screenshots/poketeams/poketeams3.png',
      '/images/screenshots/poketeams/poketeams4.png',
      '/images/screenshots/poketeams/poketeams5.png',
      '/images/screenshots/poketeams/poketeams6.png',
      '/images/screenshots/poketeams/poketeams7.png',
      '/images/screenshots/poketeams/poketeams8.png',
      '/images/screenshots/poketeams/poketeams9.png',
    ],
    description: {
      es: 'Creá tu equipo Pokémon y compartilo con el mundo. Proyecto Full-Stack desarrollado con Next.js 13.',
      en: 'Create your Pokémon Team and show it to the world. Full-Stack project developed with Next.js 13.',
    },
    features: {
      es: [
        'Pokédex con más de 1.000 Pokémon disponibles.',
        'Pokémon obtenidos de la PokeAPI.',
        'Paginación, búsqueda por nombre y filtrado por tipo.',
        'Detalles del Pokémon con botón para agregar a tu equipo.',
        'Página Teams en la que se muestran los equipos creados por la comunidad.',
        'Función de crear tu propio equipo Pokémon.',
        'Los equipos se guardan en una base de datos PostgreSQL.',
        'Generación de sitios estáticos (SSG) y renderizado del lado del servidor (SSR).',
      ],
      en: [
        'Pokédex with over 1.000 available Pokémon.',
        'Pokémon fetched from PokeAPI.',
        'Pagination, search by name and filter by type.',
        "Pokémon details with 'Add to my team' button.",
        'Teams page which lists all the teams created by the comunity.',
        'Create team functionality.',
        'Teams get stored and fetched from a PostgreSQL database.',
        'Static Site Generation (SSG) and Server Side Rendering (SSR).',
      ],
    },
    technologies: [
      'Next.js',
      'TypeScript',
      'Prisma',
      'PostgreSQL',
      'TailwindCSS',
    ],
    github: 'https://github.com/Gonzalo-Coradello/poketeams',
    deploy: 'https://poketeams-nextjs.vercel.app/',
    credits: {
      es: 'Pokémon es una marca registrada. Todos los derechos pertenecen a Nintendo y The Pokémon Company.',
      en: 'All rights belong to Nintendo and The Pokémon Company.',
    },
  },
  {
    id: '3',
    name: 'ZARA for men',
    thumbnail: '/images/zara-for-men.jpg',
    screenshots: [
      '/images/screenshots/zara-for-men/1.jpg',
      '/images/screenshots/zara-for-men/2.jpg',
      '/images/screenshots/zara-for-men/3.jpg',
      '/images/screenshots/zara-for-men/4.jpg',
      '/images/screenshots/zara-for-men/5.jpg',
      '/images/screenshots/zara-for-men/6.jpg',
    ],
    description: {
      es: 'E-commerce inspirado en ZARA, una de las principales empresas de moda internacional.',
      en: 'E-commerce inspired by ZARA, one of the biggest international fashion companies.',
    },
    features: {
      es: [
        'Acceso a los productos a través de una base de datos.',
        'Filtrado por categorías.',
        'Selección de color y talle.',
        'Galería de imágenes para cada producto.',
        'Funcionalidades de carrito completas.',
        'Detalles de la compra.',
        'Formulario de compra con validación.',
        'Con cada compra se reduce el stock de los productos en la base de datos.',
        'Almacenamiento en base de datos de las órdenes de los usuarios.',
        'Buena experiencia de usuario, diseño cuidado y atención a los detalles.',
        'Completamente responsive. Se adapta a todas las pantallas.',
      ],
      en: [
        'Products fetched from database.',
        'Filter by category.',
        'Color and size selection.',
        'Product gallery for each product.',
        'Fully functional cart.',
        'Form validation.',
        'Order details.',
        'Stock in database reduces with each order.',
        "Users' orders get stored in the database.",
        'Good user experience, polished design and attention to detail.',
        'Completely responsive.',
      ],
    },
    technologies: ['React', 'CSS', 'Firebase'],
    github: 'https://github.com/Gonzalo-Coradello/zara-for-men_ecommerce',
    deploy: 'https://zara-for-men.vercel.app',
    credits: {
      es: 'Diseño: Talia Laborde',
      en: 'Design: Talia Laborde',
    },
  },
  {
    id: '4',
    name: 'BLACKCOFFEE',
    thumbnail: '/images/blackcoffee.jpg',
    screenshots: [
      '/images/screenshots/blackcoffee/1.jpg',
      '/images/screenshots/blackcoffee/2.jpg',
      '/images/screenshots/blackcoffee/3.jpg',
      '/images/screenshots/blackcoffee/4.jpg',
      '/images/screenshots/blackcoffee/5.jpg',
      '/images/screenshots/blackcoffee/6.jpg',
      '/images/screenshots/blackcoffee/7.jpg',
      '/images/screenshots/blackcoffee/8.jpg',
      '/images/screenshots/blackcoffee/9.jpg',
    ],
    description: {
      es: 'E-commerce de BLACKCOFFEE, tostadores de café de alta calidad. Su misión es que puedas disfrutar del mejor café en la comodidad de tu hogar.',
      en: 'E-commerce for BLACKCOFFEE, high quality coffee roasters. Their mission is that you can enjoy the best coffee from the comfort of your home.',
    },
    features: {
      es: [
        'Funcionalidades de carrito completas.',
        'Detalles de la compra.',
        'Formulario de compra con validación.',
        'El carrito se preserva en el local storage.',
        'Buena experiencia de usuario, diseño pulido y atención a los detalles.',
        'Diseño responsive.',
        'Landing page.',
        'Manipulación del DOM.',
      ],
      en: [
        'Fully functional cart.',
        'Order details.',
        'Form validation.',
        'Cart is preserved in local storage.',
        'Good user experience, polished design and attention to detail.',
        'Completely responsive.',
        'Landing page.',
        'DOM manipulation.',
      ],
    },
    technologies: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/Gonzalo-Coradello/blackcoffee-ecommerce',
    deploy: 'https://blackcoffee-store.netlify.app/',
    credits: {
      es: 'Diseño, branding y logo: Talia Laborde',
      en: 'Branding, logo and design: Talia Laborde',
    },
  },
  {
    id: '5',
    name: 'To-do app',
    thumbnail: '/images/to-do-mern.jpg',
    screenshots: [
      '/images/screenshots/to-do-app/1.jpg',
      '/images/screenshots/to-do-app/2.jpg',
    ],
    description: {
      es: 'Aplicación de lista de tareas Full-Stack con autenticación de usuarios.',
      en: 'Full-Stack to-do app with user authentication.',
    },
    features: {
      es: [
        'Sistema de registro de usuarios e inicio de sesión.',
        'Autenticación y autorización.',
        'Implementaciones de seguridad: hash de contraseñas y JSON Web Tokens.',
        'Persistencia de usuarios y tareas en base de datos de MongoDB.',
        'CRUD Full-Stack.',
        'Stack MERN.',
      ],
      en: [
        'Login/register functionality.',
        'Authentication and Authorization.',
        'Security measures: password hashing and JSON Web Tokens.',
        'Users and tasks get stored in MongoDB database.',
        'Full-Stack CRUD.',
        'MERN stack.',
      ],
    },
    technologies: ['MongoDB', 'Express', 'React', 'Node.js', 'MUI'],
    github: 'https://github.com/Gonzalo-Coradello/to-do_mern',
    deploy: 'https://to-do-mern.vercel.app/',
  },
]

const ProjectsContainer = () => {
  return <Projects projects={projects} />
}

export default ProjectsContainer
